import pickle
import os
# 读取 pkl 文件
with open("/mnt/data/310_jiarui/VLABench/VLABench/configs/deterministic_config.pkl", "rb") as f:
    loaded_config = pickle.load(f)
    # 打印整个配置
    print(loaded_config)

    # 或者打印特定部分
    print(loaded_config["task"])  # 如果配置是字典格式

    # 或者逐层检查
    for key, value in loaded_config.items():
        print(f"Key: {key}")
        print(f"Value: {value}")
        print("---")


"""

{'task': {'ngrid': [10, 10], 'random_ignored_entities': ['apple', 'banana', 'orange', 'pear'], 'asset': {'seen_object': ['apple', 'banana', 'orange', 'pear'], 'unseen_object': ['peach', 'lemon', 'kiwi', 'mango'], 'seen_container': ['plate_seen'], 'unseen_container': ['plate_unseen'], 'seen_init_container': ['tray_seen'], 'unseen_init_container': ['tray_unseen']}, 'components': [{'name': 'table', 'xml_path': 'obj/meshes/table/table.xml', 'class': 'Table', 'randomness': {'texture': False}}, {'name': 'plate_seen', 'xml_path': 'obj/meshes/tablewares/plates/plate_12/model.xml', 'position': [0, 0, 0.8], 'orientation': [0, 0, 0], 'class': <class 'VLABench.tasks.components.specific_entities.common_containers.Plate'>, 'randomness': {'pos': [0.02, 0.02, 0], 'quat': [0, 0, 0.05]}}, {'name': 'apple', 'xml_path': 'obj/meshes/fruit/apple/apple_10/model.xml', 'position': [-0.1, 0.2, 0.8], 'orientation': [0, 0, 0], 'class': <class 'VLABench.tasks.components.specific_entities.common_entities.Fruit'>, 'randomness': {'pos': [0.02, 0.02, 0], 'quat': [0, 0, 0.05]}}, {'name': 'mango', 'xml_path': 'obj/meshes/fruit/mango/mango_14/model.xml', 'position': [0.0, 0.2, 0.8], 'orientation': [0, 0, 0], 'class': <class 'VLABench.tasks.components.specific_entities.common_entities.Fruit'>, 'randomness': {'pos': [0.02, 0.02, 0], 'quat': [0, 0, 0.05]}}, {'name': 'kiwi', 'xml_path': 'obj/meshes/fruit/kiwi/kiwi_4/model.xml', 'position': [0.1, 0.2, 0.8], 'orientation': [0, 0, 0], 'class': <class 'VLABench.tasks.components.specific_entities.common_entities.Fruit'>, 'randomness': {'pos': [0.02, 0.02, 0], 'quat': [0, 0, 0.05]}}], 'scene': {'name': 'studyroom_0'}, 'conditions': {'contain': {'container': 'plate_seen', 'entities': ['apple']}}, 'instructions': ['Put the apple into the plate_seen']}, 'engine': {'option': {'impratio': 10, 'timestep': 0.001, 'density': 1.225, 'viscosity': 1.8e-05, 'integrator': 'implicitfast', 'flag': {'multiccd': 'enable'}}}}
{'ngrid': [10, 10], 'random_ignored_entities': ['apple', 'banana', 'orange', 'pear'], 'asset': {'seen_object': ['apple', 'banana', 'orange', 'pear'], 'unseen_object': ['peach', 'lemon', 'kiwi', 'mango'], 'seen_container': ['plate_seen'], 'unseen_container': ['plate_unseen'], 'seen_init_container': ['tray_seen'], 'unseen_init_container': ['tray_unseen']}, 'components': [{'name': 'table', 'xml_path': 'obj/meshes/table/table.xml', 'class': 'Table', 'randomness': {'texture': False}}, {'name': 'plate_seen', 'xml_path': 'obj/meshes/tablewares/plates/plate_12/model.xml', 'position': [0, 0, 0.8], 'orientation': [0, 0, 0], 'class': <class 'VLABench.tasks.components.specific_entities.common_containers.Plate'>, 'randomness': {'pos': [0.02, 0.02, 0], 'quat': [0, 0, 0.05]}}, {'name': 'apple', 'xml_path': 'obj/meshes/fruit/apple/apple_10/model.xml', 'position': [-0.1, 0.2, 0.8], 'orientation': [0, 0, 0], 'class': <class 'VLABench.tasks.components.specific_entities.common_entities.Fruit'>, 'randomness': {'pos': [0.02, 0.02, 0], 'quat': [0, 0, 0.05]}}, {'name': 'mango', 'xml_path': 'obj/meshes/fruit/mango/mango_14/model.xml', 'position': [0.0, 0.2, 0.8], 'orientation': [0, 0, 0], 'class': <class 'VLABench.tasks.components.specific_entities.common_entities.Fruit'>, 'randomness': {'pos': [0.02, 0.02, 0], 'quat': [0, 0, 0.05]}}, {'name': 'kiwi', 'xml_path': 'obj/meshes/fruit/kiwi/kiwi_4/model.xml', 'position': [0.1, 0.2, 0.8], 'orientation': [0, 0, 0], 'class': <class 'VLABench.tasks.components.specific_entities.common_entities.Fruit'>, 'randomness': {'pos': [0.02, 0.02, 0], 'quat': [0, 0, 0.05]}}], 'scene': {'name': 'studyroom_0'}, 'conditions': {'contain': {'container': 'plate_seen', 'entities': ['apple']}}, 'instructions': ['Put the apple into the plate_seen']}
Key: task
Value: {'ngrid': [10, 10], 'random_ignored_entities': ['apple', 'banana', 'orange', 'pear'], 'asset': {'seen_object': ['apple', 'banana', 'orange', 'pear'], 'unseen_object': ['peach', 'lemon', 'kiwi', 'mango'], 'seen_container': ['plate_seen'], 'unseen_container': ['plate_unseen'], 'seen_init_container': ['tray_seen'], 'unseen_init_container': ['tray_unseen']}, 'components': [{'name': 'table', 'xml_path': 'obj/meshes/table/table.xml', 'class': 'Table', 'randomness': {'texture': False}}, {'name': 'plate_seen', 'xml_path': 'obj/meshes/tablewares/plates/plate_12/model.xml', 'position': [0, 0, 0.8], 'orientation': [0, 0, 0], 'class': <class 'VLABench.tasks.components.specific_entities.common_containers.Plate'>, 'randomness': {'pos': [0.02, 0.02, 0], 'quat': [0, 0, 0.05]}}, {'name': 'apple', 'xml_path': 'obj/meshes/fruit/apple/apple_10/model.xml', 'position': [-0.1, 0.2, 0.8], 'orientation': [0, 0, 0], 'class': <class 'VLABench.tasks.components.specific_entities.common_entities.Fruit'>, 'randomness': {'pos': [0.02, 0.02, 0], 'quat': [0, 0, 0.05]}}, {'name': 'mango', 'xml_path': 'obj/meshes/fruit/mango/mango_14/model.xml', 'position': [0.0, 0.2, 0.8], 'orientation': [0, 0, 0], 'class': <class 'VLABench.tasks.components.specific_entities.common_entities.Fruit'>, 'randomness': {'pos': [0.02, 0.02, 0], 'quat': [0, 0, 0.05]}}, {'name': 'kiwi', 'xml_path': 'obj/meshes/fruit/kiwi/kiwi_4/model.xml', 'position': [0.1, 0.2, 0.8], 'orientation': [0, 0, 0], 'class': <class 'VLABench.tasks.components.specific_entities.common_entities.Fruit'>, 'randomness': {'pos': [0.02, 0.02, 0], 'quat': [0, 0, 0.05]}}], 'scene': {'name': 'studyroom_0'}, 'conditions': {'contain': {'container': 'plate_seen', 'entities': ['apple']}}, 'instructions': ['Put the apple into the plate_seen']}
---
Key: engine
Value: {'option': {'impratio': 10, 'timestep': 0.001, 'density': 1.225, 'viscosity': 1.8e-05, 'integrator': 'implicitfast', 'flag': {'multiccd': 'enable'}}}
---
{'task': {'ngrid': [10, 10], 'random_ignored_entities': ['apple', 'banana', 'orange', 'pear'], 'asset': {'seen_object': ['apple', 'banana', 'orange', 'pear'], 'unseen_object': ['peach', 'lemon', 'kiwi', 'mango'], 'seen_container': ['plate_seen'], 'unseen_container': ['plate_unseen'], 'seen_init_container': ['tray_seen'], 'unseen_init_container': ['tray_unseen']}, 'components': [{'name': 'table', 'xml_path': 'obj/meshes/table/table.xml', 'class': 'Table', 'randomness': {'texture': False}}, {'name': 'plate_seen', 'xml_path': 'obj/meshes/tablewares/plates/plate_12/model.xml', 'position': [0, 0, 0.8], 'orientation': [0, 0, 0], 'class': <class 'VLABench.tasks.components.specific_entities.common_containers.Plate'>, 'randomness': {'pos': [0.02, 0.02, 0], 'quat': [0, 0, 0.05]}}, {'name': 'apple', 'xml_path': 'obj/meshes/fruit/apple/apple_10/model.xml', 'position': [-0.1, 0.2, 0.8], 'orientation': [0, 0, 0], 'class': <class 'VLABench.tasks.components.specific_entities.common_entities.Fruit'>, 'randomness': {'pos': [0.02, 0.02, 0], 'quat': [0, 0, 0.05]}}, {'name': 'mango', 'xml_path': 'obj/meshes/fruit/mango/mango_14/model.xml', 'position': [0.0, 0.2, 0.8], 'orientation': [0, 0, 0], 'class': <class 'VLABench.tasks.components.specific_entities.common_entities.Fruit'>, 'randomness': {'pos': [0.02, 0.02, 0], 'quat': [0, 0, 0.05]}}, {'name': 'kiwi', 'xml_path': 'obj/meshes/fruit/kiwi/kiwi_4/model.xml', 'position': [0.1, 0.2, 0.8], 'orientation': [0, 0, 0], 'class': <class 'VLABench.tasks.components.specific_entities.common_entities.Fruit'>, 'randomness': {'pos': [0.02, 0.02, 0], 'quat': [0, 0, 0.05]}}], 'scene': {'name': 'studyroom_0'}, 'conditions': {'contain': {'container': 'plate_seen', 'entities': ['apple']}}, 'instructions': ['Put the apple into the plate_seen']}, 'engine': {'option': {'impratio': 10, 'timestep': 0.001, 'density': 1.225, 'viscosity': 1.8e-05, 'integrator': 'implicitfast', 'flag': {'multiccd': 'enable'}}}}
{'ngrid': [10, 10], 'random_ignored_entities': ['apple', 'banana', 'orange', 'pear'], 'asset': {'seen_object': ['apple', 'banana', 'orange', 'pear'], 'unseen_object': ['peach', 'lemon', 'kiwi', 'mango'], 'seen_container': ['plate_seen'], 'unseen_container': ['plate_unseen'], 'seen_init_container': ['tray_seen'], 'unseen_init_container': ['tray_unseen']}, 'components': [{'name': 'table', 'xml_path': 'obj/meshes/table/table.xml', 'class': 'Table', 'randomness': {'texture': False}}, {'name': 'plate_seen', 'xml_path': 'obj/meshes/tablewares/plates/plate_12/model.xml', 'position': [0, 0, 0.8], 'orientation': [0, 0, 0], 'class': <class 'VLABench.tasks.components.specific_entities.common_containers.Plate'>, 'randomness': {'pos': [0.02, 0.02, 0], 'quat': [0, 0, 0.05]}}, {'name': 'apple', 'xml_path': 'obj/meshes/fruit/apple/apple_10/model.xml', 'position': [-0.1, 0.2, 0.8], 'orientation': [0, 0, 0], 'class': <class 'VLABench.tasks.components.specific_entities.common_entities.Fruit'>, 'randomness': {'pos': [0.02, 0.02, 0], 'quat': [0, 0, 0.05]}}, {'name': 'mango', 'xml_path': 'obj/meshes/fruit/mango/mango_14/model.xml', 'position': [0.0, 0.2, 0.8], 'orientation': [0, 0, 0], 'class': <class 'VLABench.tasks.components.specific_entities.common_entities.Fruit'>, 'randomness': {'pos': [0.02, 0.02, 0], 'quat': [0, 0, 0.05]}}, {'name': 'kiwi', 'xml_path': 'obj/meshes/fruit/kiwi/kiwi_4/model.xml', 'position': [0.1, 0.2, 0.8], 'orientation': [0, 0, 0], 'class': <class 'VLABench.tasks.components.specific_entities.common_entities.Fruit'>, 'randomness': {'pos': [0.02, 0.02, 0], 'quat': [0, 0, 0.05]}}], 'scene': {'name': 'studyroom_0'}, 'conditions': {'contain': {'container': 'plate_seen', 'entities': ['apple']}}, 'instructions': ['Put the apple into the plate_seen']}
Key: task
Value: {'ngrid': [10, 10], 'random_ignored_entities': ['apple', 'banana', 'orange', 'pear'], 'asset': {'seen_object': ['apple', 'banana', 'orange', 'pear'], 'unseen_object': ['peach', 'lemon', 'kiwi', 'mango'], 'seen_container': ['plate_seen'], 'unseen_container': ['plate_unseen'], 'seen_init_container': ['tray_seen'], 'unseen_init_container': ['tray_unseen']}, 'components': [{'name': 'table', 'xml_path': 'obj/meshes/table/table.xml', 'class': 'Table', 'randomness': {'texture': False}}, {'name': 'plate_seen', 'xml_path': 'obj/meshes/tablewares/plates/plate_12/model.xml', 'position': [0, 0, 0.8], 'orientation': [0, 0, 0], 'class': <class 'VLABench.tasks.components.specific_entities.common_containers.Plate'>, 'randomness': {'pos': [0.02, 0.02, 0], 'quat': [0, 0, 0.05]}}, {'name': 'apple', 'xml_path': 'obj/meshes/fruit/apple/apple_10/model.xml', 'position': [-0.1, 0.2, 0.8], 'orientation': [0, 0, 0], 'class': <class 'VLABench.tasks.components.specific_entities.common_entities.Fruit'>, 'randomness': {'pos': [0.02, 0.02, 0], 'quat': [0, 0, 0.05]}}, {'name': 'mango', 'xml_path': 'obj/meshes/fruit/mango/mango_14/model.xml', 'position': [0.0, 0.2, 0.8], 'orientation': [0, 0, 0], 'class': <class 'VLABench.tasks.components.specific_entities.common_entities.Fruit'>, 'randomness': {'pos': [0.02, 0.02, 0], 'quat': [0, 0, 0.05]}}, {'name': 'kiwi', 'xml_path': 'obj/meshes/fruit/kiwi/kiwi_4/model.xml', 'position': [0.1, 0.2, 0.8], 'orientation': [0, 0, 0], 'class': <class 'VLABench.tasks.components.specific_entities.common_entities.Fruit'>, 'randomness': {'pos': [0.02, 0.02, 0], 'quat': [0, 0, 0.05]}}], 'scene': {'name': 'studyroom_0'}, 'conditions': {'contain': {'container': 'plate_seen', 'entities': ['apple']}}, 'instructions': ['Put the apple into the plate_seen']}
---
Key: engine
Value: {'option': {'impratio': 10, 'timestep': 0.001, 'density': 1.225, 'viscosity': 1.8e-05, 'integrator': 'implicitfast', 'flag': {'multiccd': 'enable'}}}
---
"""